package com.shipping.views;
import controller.ShippingController;
import com.shipping.controller.SelectionSort;
import com.shipping.controller.InsertionSort;
import com.shipping.model.Shipping;
import java.awt.HeadlessException;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author navo
 */
public class shippingmain extends javax.swing.JFrame {
    private final LinkedList<Shipping> shiplist;
    private final ShippingController Merge = new ShippingController();
    private final SelectionSort Selection = new SelectionSort();
    private final InsertionSort Insertion = new InsertionSort();
    public shippingmain() {
        initComponents();
        shiplist = new LinkedList();
        addshippingdata(new Shipping(1,"Kathmandu", "Lalitpur","Vanasthali", "Rithepani", "9818218445"));
        addshippingdata(new Shipping(2,"Pokhara", "Chitwan","Sauraha", "SimalChaur", "981231100"));
        addshippingdata(new Shipping(3,"Lalitpur", "Biratnagar","Sauraha", "SimalChaur", "981231100"));
        addshippingdata(new Shipping(4,"Chitwan", "Kathmandu","Sauraha", "SimalChaur", "981231100"));
        addshippingdata(new Shipping(5,"Biratnagar", "Pokhara","Sauraha", "SimalChaur", "981231100"));
        panelmain.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginpage = new javax.swing.JPanel();
        usernametxtfield = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        passwordtxtfield = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        loginbtn = new javax.swing.JButton();
        LOGIN = new javax.swing.JLabel();
        panelmain = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel67 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        fromoption = new javax.swing.JComboBox<>();
        numbertxtfield = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        create = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        tooption = new javax.swing.JComboBox<>();
        droptxtfield = new javax.swing.JTextField();
        pickuptxtfield = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblship = new javax.swing.JTable();
        shipnotxtfield = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        sort1 = new javax.swing.JButton();
        search = new javax.swing.JButton();
        searchtxtfield = new javax.swing.JTextField();
        sort2 = new javax.swing.JToggleButton();
        sortcombobox = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        footer = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loginpage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        loginpage.add(usernametxtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 230, 180, -1));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Username:");
        loginpage.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, 70, -1));
        loginpage.add(passwordtxtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, 180, -1));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Password:");
        loginpage.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 290, 60, -1));

        loginbtn.setText("Login");
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });
        loginpage.add(loginbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, -1, -1));

        LOGIN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shipping/views/Login1.png"))); // NOI18N
        loginpage.add(LOGIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        panelmain.setBackground(new java.awt.Color(55, 52, 65));
        panelmain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(66, 62, 78));

        jLabel1.setText("Home");

        jLabel2.setText("About");

        jLabel3.setText("Contact us");

        jButton1.setText("Log Out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Shipment");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Shipment");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shipping/views/Screenshot_2024-12-26_144041-removebg-preview.png"))); // NOI18N
        jLabel8.setText("jLabel8");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(21, 21, 21)
                .addComponent(jButton1)
                .addContainerGap())
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel5))
                    .addGroup(headerLayout.createSequentialGroup()
                        .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(headerLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jButton1)))
                            .addGroup(headerLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel8)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        panelmain.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 7, 1209, -1));

        jTabbedPane1.setBackground(new java.awt.Color(236, 163, 116));

        jPanel3.setBackground(new java.awt.Color(55, 52, 65));

        jLabel67.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(255, 255, 255));
        jLabel67.setText("We Make your Shipping Easier");

        jLabel69.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(255, 255, 255));
        jLabel69.setText("Faster than ever");

        jLabel68.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(255, 255, 255));
        jLabel68.setText("Try our services");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel67, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel69, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel68, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1152, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel67, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel69, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel68, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(302, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Introduction", jPanel3);

        jLabel6.setText("From:");

        jLabel9.setText("Pickup Location:");

        fromoption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kathmandu", "Pokhara", "Lalitpur", "Bhaktapur", "Biratnagar", "Birgunj", "Dharan", "Butwal", "Hetauda", "Dhangadhi", "Janakpur", "Nepalgunj", "Itahari", "Bharatpur", "Baglung", "Ghorahi", "Tulsipur", "Bhadrapur", "Rajbiraj", "Ilam" }));

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        create.setText("Create Order");
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        jLabel10.setText("Drop Location:");

        tooption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kathmandu", "Pokhara", "Lalitpur", "Bhaktapur", "Biratnagar", "Birgunj", "Dharan", "Butwal", "Hetauda", "Dhangadhi", "Janakpur", "Nepalgunj", "Itahari", "Bharatpur", "Baglung", "Ghorahi", "Tulsipur", "Bhadrapur", "Rajbiraj", "Ilam" }));

        jLabel11.setText("Number:");

        jLabel7.setText("To:");

        tblship.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Ship.No", "From", "To", "Pickup Location", "Drop Location", "Number"
            }
        ));
        jScrollPane2.setViewportView(tblship);

        jLabel22.setText("Ship Number:");

        sort1.setText("Sort by Ascending");
        sort1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sort1ActionPerformed(evt);
            }
        });

        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        searchtxtfield.setText("Enter Ship no.");
        searchtxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchtxtfieldActionPerformed(evt);
            }
        });

        sort2.setText("Sort by Descending");
        sort2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sort2ActionPerformed(evt);
            }
        });

        sortcombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sort by Ship. no", "Sort by From Location", "Sort by To Location", " " }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(tooption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(delete)
                                    .addComponent(fromoption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(89, 89, 89))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(154, 154, 154)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(update)
                            .addComponent(jLabel9)
                            .addComponent(pickuptxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addComponent(shipnotxtfield, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(create)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(droptxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numbertxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addGap(101, 101, 101)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sort2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sort1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sortcombobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(searchtxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(search)))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel22))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fromoption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shipnotxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(delete))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(pickuptxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tooption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(update))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(searchtxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sortcombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(droptxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numbertxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sort1)
                            .addComponent(search))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(create)
                            .addComponent(sort2))))
                .addGap(177, 177, 177))
        );

        jTabbedPane1.addTab("Ship logs", jPanel5);

        panelmain.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 110, 1210, 406));

        jPanel6.setBackground(new java.awt.Color(255, 204, 0));

        jLabel65.setBackground(new java.awt.Color(255, 255, 255));
        jLabel65.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(255, 255, 255));
        jLabel65.setText("Let's Make Shipping Easier!");

        jLabel66.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(255, 255, 255));
        jLabel66.setText("Get in touch >");

        footer.setBackground(new java.awt.Color(168, 159, 200));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("About");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Our Services");

        jLabel16.setText("About us");

        jLabel17.setText("Our Work");

        jLabel18.setText("Contact us");

        jLabel19.setText("Blog");

        jLabel20.setText("Cargo Shipping");

        jLabel21.setText("Air Shipping");

        jPanel7.setBackground(new java.awt.Color(255, 204, 0));

        jLabel70.setBackground(new java.awt.Color(255, 255, 255));
        jLabel70.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(255, 255, 255));
        jLabel70.setText("Let's Make Shipping Easier!");

        jLabel71.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(255, 255, 255));
        jLabel71.setText("Get in touch >");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel70, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel71, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel70)
                .addGap(18, 18, 18)
                .addComponent(jLabel71)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout footerLayout = new javax.swing.GroupLayout(footer);
        footer.setLayout(footerLayout);
        footerLayout.setHorizontalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerLayout.createSequentialGroup()
                .addContainerGap(583, Short.MAX_VALUE)
                .addComponent(jLabel64, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(560, 560, 560))
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(footerLayout.createSequentialGroup()
                .addGap(409, 409, 409)
                .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addGroup(footerLayout.createSequentialGroup()
                        .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel20))))
                .addContainerGap())
        );
        footerLayout.setVerticalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(11, 11, 11)
                .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(jLabel64)
                .addContainerGap(250, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel66, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(footer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel65)
                .addGap(18, 18, 18)
                .addComponent(jLabel66)
                .addContainerGap(474, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(footer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panelmain.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 528, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelmain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(loginpage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelmain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(loginpage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed

        try{int number = Integer.parseInt(shipnotxtfield.getText());
            if(deleteship(number)==true){
                JOptionPane.showMessageDialog(this,"Shipping Details Deleted Successfully!!","Successful",JOptionPane.INFORMATION_MESSAGE);
                loadshiptable();
            }
            else if (shipnotxtfield.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ship number cannot be empty!", "Validation Error", JOptionPane.ERROR_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(this,"Error","Error",JOptionPane.ERROR_MESSAGE);
            }
        }
        catch (NumberFormatException e) {
            // Handle invalid input for JobId
            JOptionPane.showMessageDialog(this, "Invalid ship no. Please enter a valid number!", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (HeadlessException e) {
            // Catch any other unexpected exceptions
            JOptionPane.showMessageDialog(this, "An error occurred while deleting the job.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed

    try {
        // Validate Ship Number
        if (shipnotxtfield.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ship number cannot be empty!", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int shipno = Integer.parseInt(shipnotxtfield.getText());

        // Validate From and To
        String from = (String) fromoption.getSelectedItem();
        String to = (String) tooption.getSelectedItem();
        if (from == null || from.isEmpty() || to == null || to.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Both 'From' and 'To' locations must be selected!", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validate Pickup and Drop Locations
        String pickup = pickuptxtfield.getText();
        String drop = droptxtfield.getText();
        if (pickup.isEmpty() || drop.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pickup and Drop locations cannot be empty!", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validate Contact Number
        String number = numbertxtfield.getText();
        if (number.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Contact number cannot be empty!", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!number.matches("\\d+")) { // Ensures the number contains only digits
            JOptionPane.showMessageDialog(this, "Contact number must contain only digits!", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Create and Add Shipping Data
        Shipping shipping = new Shipping(shipno, from, to, drop, pickup, number);
        addshippingdata(shipping);

        // Show Success Message
        JOptionPane.showMessageDialog(this, "Shipping data added successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } catch (NumberFormatException e) {
        // Handles invalid Ship Number input
        JOptionPane.showMessageDialog(this, "Ship number must be a valid integer!", "Input Error", JOptionPane.ERROR_MESSAGE);
    } catch (IllegalArgumentException e) {
        // Handles any validation errors
        JOptionPane.showMessageDialog(this, e.getMessage(), "Validation Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        // Catch any other unexpected errors
        JOptionPane.showMessageDialog(this, "An unexpected error occurred: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_createActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        
        try{//get input from text fields
            int shipno = Integer.parseInt(shipnotxtfield.getText());
            String from = (String) fromoption.getSelectedItem();
            String to = (String) tooption.getSelectedItem();
            String pickup = pickuptxtfield.getText();
            String drop = droptxtfield.getText();
            String no = numbertxtfield.getText();
            if (from.isEmpty()||to.isEmpty()||pickup.isEmpty()||drop.isEmpty()||no.isEmpty()){
                //Error message for empty text fields
                JOptionPane.showMessageDialog(this,"Please Fill All The Fields,Shipping details not added","Error",JOptionPane.ERROR_MESSAGE);
            }
            else{
                Shipping updateshipa=new Shipping(shipno,from,to,  pickup,  drop,  no);
                updateship(updateshipa);
                loadshiptable(); //refresh table after updating
                JOptionPane.showMessageDialog(this,"Shipping Details Updated", "Successful", JOptionPane.INFORMATION_MESSAGE);
            }}
            catch (HeadlessException e) {
                // Handle any other unexpected exceptions
                JOptionPane.showMessageDialog(this, "ERROR!!", "Error", JOptionPane.ERROR_MESSAGE);
                // Optionally print the stack trace for debugging
            }
    }//GEN-LAST:event_updateActionPerformed

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
     String username = usernametxtfield.getText();
        String password = passwordtxtfield.getText();
        if(username.isEmpty() && password.isEmpty() ){
            JOptionPane.showMessageDialog(null, "Please enter both username and password.", "Login Error", JOptionPane.ERROR_MESSAGE);
        }
        else if(!username.equals("admin")||!password.equals("admin")){
            JOptionPane.showMessageDialog(null, "Username or Password is incorrect", "Login Error", JOptionPane.ERROR_MESSAGE);
        }
        else {
            panelmain.setVisible(true);
            loginpage.setVerifyInputWhenFocusTarget(false);

        }
    }//GEN-LAST:event_loginbtnActionPerformed

    private void sort1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sort1ActionPerformed
    String sortoption = (String) sortcombobox.getSelectedItem();
    if(sortoption == "Sort by Ship. no"){
    Merge.mergeSort(shiplist, true);  // Sort in ascending order
    loadshiptable(); // Refresh the table
    JOptionPane.showMessageDialog(this, "Data Sorted in Ascending Order!", "Sort Successful", JOptionPane.INFORMATION_MESSAGE);
    }
    else if(sortoption == "Sort by From Location"){
    Selection.selectionSortByFrom(shiplist, true); // Sort in descending order
    loadshiptable(); // Refresh the table
    JOptionPane.showMessageDialog(this, "Sorted by 'From' in Ascending Order!", "Sort", JOptionPane.INFORMATION_MESSAGE);
    }
    else if(sortoption == "Sort by To Location"){
    Insertion.insertionSortByTo(shiplist, true); // Sort in ascending order
    loadshiptable(); // Refresh the table
    JOptionPane.showMessageDialog(this, "Sorted by 'To' in Ascending Order!", "Sort", JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_sort1ActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
                                      
    try {
        int targetShipNo = Integer.parseInt(shipnotxtfield.getText()); // Get the ship number from the text field

        // Ensure the list is sorted before performing binary search
        Merge.mergeSort(shiplist, true); // Use the 'controller' instance
        loadshiptable();
        // Perform binary search
        String shipnoText = shipnotxtfield.getText();
        Shipping result = binarySearch(shiplist, targetShipNo);
         if (shipnoText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ship number cannot be empty!", "Validation Error", JOptionPane.ERROR_MESSAGE);
        }

        else if (result != null) {
            // Display the details of the found shipping
            JOptionPane.showMessageDialog(this,"Shipping Found:"+"\n" +"Ship No: " + result.getShipno() + "\n" + "From: " + result.getFrom() + "\n" +"To: " + result.getTo() + "\n" +"Pickup: " + result.getPickup() + "\n" +"Drop: " + result.getDrop() + "\n" + "Number: " + result.getNumber(),"Search Result",JOptionPane.INFORMATION_MESSAGE);
        } 
        else {
            // Show a message if the shipping object is not found
            JOptionPane.showMessageDialog(this, "Shipping Not Found!", "Search Result", JOptionPane.ERROR_MESSAGE);
        }
    } catch (NumberFormatException e) {
        // Handle invalid input
        JOptionPane.showMessageDialog(this, "Please enter a valid Ship No!", "Error", JOptionPane.ERROR_MESSAGE);
    }


    }//GEN-LAST:event_searchActionPerformed

    private void searchtxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchtxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchtxtfieldActionPerformed

    private void sort2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sort2ActionPerformed
    String sortoption = (String) sortcombobox.getSelectedItem();
    if(sortoption == "Sort by Ship. no"){
    Merge.mergeSort(shiplist, false); // Sort in descending order
    loadshiptable(); // Refresh the table
    JOptionPane.showMessageDialog(this, "Data Sorted in Descending Order!", "Sort Successful", JOptionPane.INFORMATION_MESSAGE);
    }
    else if(sortoption == "Sort by From Location"){
    Selection.selectionSortByFrom(shiplist, false); // Sort in descending order
    loadshiptable(); // Refresh the table
    JOptionPane.showMessageDialog(this, "Sorted by 'From' in Descending Order!", "Sort", JOptionPane.INFORMATION_MESSAGE);
    }
    else if(sortoption == "Sort by To Location"){
    Insertion.insertionSortByTo(shiplist, false); // Sort in ascending order
    loadshiptable(); // Refresh the table
    JOptionPane.showMessageDialog(this, "Sorted by 'To' in Descending Order!", "Sort", JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_sort2ActionPerformed

    /**
     * @param args the command line arguments
     */
    private void addshippingdata(Shipping ship) {
        shiplist.add(ship);
        //Table add
        DefaultTableModel defaultTableModel = (DefaultTableModel) tblship.getModel();
        defaultTableModel.addRow(new Object[]{
        ship.getShipno(),ship.getFrom(), ship.getTo(), ship.getPickup(),ship.getDrop(), ship.getNumber()
        });
    }
    private Boolean deleteship(int number) {
    for (int i = 0; i < shiplist.size(); i++) {
        if (shiplist.get(i).getShipno() == number) {
            shiplist.remove(i); // Remove the ship at the current index
            return true; // Ship found and deleted
        }
    }
    return false; // Ship not found
}
    
    public void loadshiptable(){
     DefaultTableModel model = (DefaultTableModel) tblship.getModel();
    model.setRowCount(0);
    for (Shipping ship:shiplist){
        model.addRow(new Object[]{ship.getShipno(), ship.getFrom() ,  ship.getTo(), ship.getPickup(),ship.getDrop() ,ship.getNumber()});
        
    }};
    private Boolean updateship(Shipping ship){
        int shipnumber = ship.getShipno();
        for (Shipping shipupdate:shiplist){
          if(shipnumber==shipupdate.getShipno()){
             shipupdate.setFrom(ship.getFrom());
             shipupdate.setTo(ship.getTo());
             shipupdate.setPickup(ship.getPickup());
             shipupdate.setDrop(ship.getDrop());
             shipupdate.setNumber(ship.getNumber());
              return true;
              }
        }
     return false;
     }
            private Shipping binarySearch(LinkedList<Shipping> list, int target) {
            int low = 0;
            int high = list.size() - 1;

            while (low <= high) {
                int mid = low + (high - low) / 2;
                Shipping midShipping = list.get(mid); // Access mid element

                if (midShipping.getShipno() == target) {
                    return midShipping; // Found the target
                } else if (midShipping.getShipno() < target) {
                    low = mid + 1; // Search in the right half
                } else {
                    high = mid - 1; // Search in the left half
                }
            }
            return null; // Target not found
        }


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(shippingmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(shippingmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(shippingmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(shippingmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new shippingmain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LOGIN;
    private javax.swing.JButton create;
    private javax.swing.JButton delete;
    private javax.swing.JTextField droptxtfield;
    private javax.swing.JPanel footer;
    private javax.swing.JComboBox<String> fromoption;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton loginbtn;
    private javax.swing.JPanel loginpage;
    private javax.swing.JTextField numbertxtfield;
    private javax.swing.JPanel panelmain;
    private javax.swing.JTextField passwordtxtfield;
    private javax.swing.JTextField pickuptxtfield;
    private javax.swing.JButton search;
    private javax.swing.JTextField searchtxtfield;
    private javax.swing.JTextField shipnotxtfield;
    private javax.swing.JButton sort1;
    private javax.swing.JToggleButton sort2;
    private javax.swing.JComboBox<String> sortcombobox;
    private javax.swing.JTable tblship;
    private javax.swing.JComboBox<String> tooption;
    private javax.swing.JButton update;
    private javax.swing.JTextField usernametxtfield;
    // End of variables declaration//GEN-END:variables
}
