/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.shipping.views; 

import com.shipping.model.Shipping;
import java.awt.HeadlessException;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Navodit Malla 23048625
 */
public class shippingmain extends javax.swing.JFrame {

    /**
     * Creates new form shippingmain
     */
    private final LinkedList<Shipping> shiplist;
       public shippingmain() {
        initComponents();
        shiplist = new LinkedList();
        addshippingdata(new Shipping("Kathmandu", "Pokhara","Vanasthali", "Rithepani", "9818218445"));
        addshippingdata(new Shipping("Chitwan", "Pokhara","Sauraha", "SimalChaur", "981231100"));
        addshippingdata(new Shipping("Chitwan", "Pokhara","Sauraha", "SimalChaur", "981231100"));
        addshippingdata(new Shipping("Chitwan", "Pokhara","Sauraha", "SimalChaur", "981231100"));
        addshippingdata(new Shipping("Chitwan", "Pokhara","Sauraha", "SimalChaur", "981231100"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @param args
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        loginpage = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        passwordtxtfield = new javax.swing.JPasswordField();
        usernametxtfield = new javax.swing.JTextField();
        loginbutton = new javax.swing.JButton();
        loginbackground = new javax.swing.JLabel();
        panelmain = new javax.swing.JPanel();
        logo3 = new javax.swing.JLabel();
        ship6 = new javax.swing.JLabel();
        ship7 = new javax.swing.JLabel();
        header3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        login3 = new javax.swing.JButton();
        footer = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        tabpane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        businessship = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        fromoption = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        tooption = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        droptxtfield = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        numbertxtfield = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        pickuptxtfield = new javax.swing.JTextArea();
        create = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        shiplog = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblship = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        loginpage.setMaximumSize(new java.awt.Dimension(1980, 1080));
        loginpage.setPreferredSize(new java.awt.Dimension(1980, 1080));
        loginpage.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Password:");
        loginpage.add(jLabel1);
        jLabel1.setBounds(620, 280, 80, 16);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username:");
        loginpage.add(jLabel2);
        jLabel2.setBounds(620, 200, 80, 16);
        loginpage.add(passwordtxtfield);
        passwordtxtfield.setBounds(620, 310, 190, 22);

        usernametxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernametxtfieldActionPerformed(evt);
            }
        });
        loginpage.add(usernametxtfield);
        usernametxtfield.setBounds(620, 230, 190, 22);

        loginbutton.setText("Login");
        loginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbuttonActionPerformed(evt);
            }
        });
        loginpage.add(loginbutton);
        loginbutton.setBounds(620, 410, 190, 23);

        loginbackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shipping/resources/LOGIN.png"))); // NOI18N
        loginbackground.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginpage.add(loginbackground);
        loginbackground.setBounds(-500, 0, 1430, 549);

        panelmain.setBackground(new java.awt.Color(55, 52, 65));
        panelmain.setForeground(new java.awt.Color(51, 51, 51));
        panelmain.setAlignmentX(50.0F);
        panelmain.setAlignmentY(0.0F);
        panelmain.setMaximumSize(new java.awt.Dimension(2000, 900));
        panelmain.setPreferredSize(new java.awt.Dimension(1080, 858));
        panelmain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shipping/resources/Screenshot_2024-12-26_144041-removebg-preview.png"))); // NOI18N
        panelmain.add(logo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 80));

        ship6.setForeground(new java.awt.Color(204, 204, 204));
        ship6.setText("Shipmentday");
        panelmain.add(ship6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 79, -1));

        ship7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ship7.setForeground(new java.awt.Color(153, 153, 153));
        ship7.setText("Shipmentday");
        panelmain.add(ship7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 90, -1));

        header3.setBackground(new java.awt.Color(66, 62, 78));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Home");

        jLabel11.setText("About");

        jLabel12.setText("Services");

        jLabel13.setText("Contact us");

        login3.setText("Logout");
        login3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout header3Layout = new javax.swing.GroupLayout(header3);
        header3.setLayout(header3Layout);
        header3Layout.setHorizontalGroup(
            header3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header3Layout.createSequentialGroup()
                .addContainerGap(619, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addGap(15, 15, 15)
                .addComponent(jLabel13)
                .addGap(58, 58, 58)
                .addComponent(login3)
                .addGap(69, 69, 69))
        );
        header3Layout.setVerticalGroup(
            header3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header3Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(header3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(login3))
                .addGap(18, 18, 18))
        );

        panelmain.add(header3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 70));

        footer.setBackground(new java.awt.Color(168, 159, 200));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("About");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Our Services");

        jLabel16.setText("About us");

        jLabel17.setText("Our Work");

        jLabel18.setText("Contact us");

        jLabel19.setText("Blog");

        jLabel20.setText("Cargo Shipping");

        jLabel21.setText("Air Shipping");

        jPanel3.setBackground(new java.awt.Color(255, 204, 0));

        jLabel65.setBackground(new java.awt.Color(255, 255, 255));
        jLabel65.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(255, 255, 255));
        jLabel65.setText("Let's Make Shipping Easier!");

        jLabel66.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(255, 255, 255));
        jLabel66.setText("Get in touch >");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel66, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel65)
                .addGap(18, 18, 18)
                .addComponent(jLabel66)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout footerLayout = new javax.swing.GroupLayout(footer);
        footer.setLayout(footerLayout);
        footerLayout.setHorizontalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerLayout.createSequentialGroup()
                .addContainerGap(492, Short.MAX_VALUE)
                .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addGroup(footerLayout.createSequentialGroup()
                        .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel64, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel20))))
                .addGap(362, 362, 362))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        footerLayout.setVerticalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(footerLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel64))
                    .addGroup(footerLayout.createSequentialGroup()
                        .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(11, 11, 11)
                        .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel18)))
                .addContainerGap(170, Short.MAX_VALUE))
        );

        panelmain.add(footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 1030, 420));

        tabpane.setBackground(new java.awt.Color(236, 163, 116));

        jPanel1.setBackground(new java.awt.Color(55, 52, 65));

        jLabel67.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(255, 255, 255));
        jLabel67.setText("We Make your Shipping Easier");

        jLabel68.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(255, 255, 255));
        jLabel68.setText("Try our services");

        jLabel69.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(255, 255, 255));
        jLabel69.setText("Faster than ever");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel67, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel68, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel69, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(649, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel67, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel69, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel68, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(267, Short.MAX_VALUE))
        );

        tabpane.addTab("Introduction", jPanel1);

        businessship.setBackground(new java.awt.Color(55, 52, 65));

        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("From:");

        fromoption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kathmandu", "Pokhara", "Lalitpur", "Bhaktapur", "Biratnagar", "Birgunj", "Dharan", "Butwal", "Hetauda", "Dhangadhi", "Janakpur", "Nepalgunj", "Itahari", "Bharatpur", "Baglung", "Ghorahi", "Tulsipur", "Bhadrapur", "Rajbiraj", "Ilam" }));

        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("To:");

        tooption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kathmandu", "Pokhara", "Lalitpur", "Bhaktapur", "Biratnagar", "Birgunj", "Dharan", "Butwal", "Hetauda", "Dhangadhi", "Janakpur", "Nepalgunj", "Itahari", "Bharatpur", "Baglung", "Ghorahi", "Tulsipur", "Bhadrapur", "Rajbiraj", "Ilam" }));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Drop Location:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(204, 204, 204))); // NOI18N
        jScrollPane1.setForeground(new java.awt.Color(204, 204, 204));

        droptxtfield.setColumns(20);
        droptxtfield.setRows(5);
        jScrollPane1.setViewportView(droptxtfield);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Number:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(204, 204, 204))); // NOI18N

        numbertxtfield.setColumns(20);
        numbertxtfield.setRows(5);
        jScrollPane2.setViewportView(numbertxtfield);

        jScrollPane4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pickup Location:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(204, 204, 204))); // NOI18N

        pickuptxtfield.setColumns(20);
        pickuptxtfield.setRows(5);
        jScrollPane4.setViewportView(pickuptxtfield);

        create.setText("Create Order");
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout businessshipLayout = new javax.swing.GroupLayout(businessship);
        businessship.setLayout(businessshipLayout);
        businessshipLayout.setHorizontalGroup(
            businessshipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(businessshipLayout.createSequentialGroup()
                .addGroup(businessshipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(businessshipLayout.createSequentialGroup()
                        .addGroup(businessshipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tooption, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(businessshipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(businessshipLayout.createSequentialGroup()
                                    .addGap(25, 25, 25)
                                    .addComponent(fromoption, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(businessshipLayout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addGroup(businessshipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(49, 49, 49)
                        .addGroup(businessshipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(businessshipLayout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(businessshipLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(create, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(347, Short.MAX_VALUE))
        );
        businessshipLayout.setVerticalGroup(
            businessshipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(businessshipLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(businessshipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(businessshipLayout.createSequentialGroup()
                        .addComponent(fromoption, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tooption, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(businessshipLayout.createSequentialGroup()
                        .addGroup(businessshipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(businessshipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(create, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(168, Short.MAX_VALUE))
        );

        tabpane.addTab("Business", businessship);

        tblship.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "From", "To", "Pickup Location", "Drop Location", "Number"
            }
        ));
        jScrollPane3.setViewportView(tblship);

        javax.swing.GroupLayout shiplogLayout = new javax.swing.GroupLayout(shiplog);
        shiplog.setLayout(shiplogLayout);
        shiplogLayout.setHorizontalGroup(
            shiplogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1040, Short.MAX_VALUE)
        );
        shiplogLayout.setVerticalGroup(
            shiplogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
        );

        tabpane.addTab("Ship logs", shiplog);

        panelmain.add(tabpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1040, 500));
        panelmain.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, -1, -1));

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addComponent(panelmain, javax.swing.GroupLayout.PREFERRED_SIZE, 1031, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 176, Short.MAX_VALUE))
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame1Layout.createSequentialGroup()
                    .addGap(75, 75, 75)
                    .addComponent(loginpage, javax.swing.GroupLayout.PREFERRED_SIZE, 1132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addComponent(panelmain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(loginpage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE))
        );

        setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 752, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 455, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        String number = numbertxtfield.getText();
        deleteship(number);
        try{
            if(deleteship(number)==true){
                JOptionPane.showMessageDialog(this,"Shipping Details Deleted Successfully!!","Successful",JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(this,"Error","Error",JOptionPane.ERROR_MESSAGE);
            }
        }
        catch (NumberFormatException e) {
            // Handle invalid input for JobId
            JOptionPane.showMessageDialog(this, "Invalid Job ID. Please enter a valid number!", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (HeadlessException e) {
            // Catch any other unexpected exceptions
            JOptionPane.showMessageDialog(this, "An error occurred while deleting the job.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        String from = (String) fromoption.getSelectedItem();
        String to = (String) fromoption.getSelectedItem();
        String pickup = pickuptxtfield.getText();
        String drop = droptxtfield.getText();
        String no = numbertxtfield.getText();
        try{
            if (from.isEmpty()||to.isEmpty()||pickup.isEmpty()||drop.isEmpty()||no.isEmpty()){
                JOptionPane.showMessageDialog(this,"Please Fill All The Fields,Shipping details not added","Error",JOptionPane.ERROR_MESSAGE);
            }
            else{
                Shipping updateship=new Shipping(from,  to,  pickup,  drop,  no);
                updateship(updateship);
                JOptionPane.showMessageDialog(this,"Shipping Details Updated", "Successful", JOptionPane.INFORMATION_MESSAGE);
            }}
            catch (HeadlessException e) {
                // Handle any other unexpected exceptions
                JOptionPane.showMessageDialog(this, "ERROR!!", "Error", JOptionPane.ERROR_MESSAGE);
                // Optionally print the stack trace for debugging
            }
    }//GEN-LAST:event_updateActionPerformed

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        String from=(String) fromoption.getSelectedItem();
        String to=(String) tooption.getSelectedItem();
        String drop=droptxtfield.getText();
        String pickup=pickuptxtfield.getText();
        String number=numbertxtfield.getText();
        Shipping shipping=new Shipping(from,to, drop,pickup,number);
        registership(shipping);

    }//GEN-LAST:event_createActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginActionPerformed

    private void loginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbuttonActionPerformed
        String username = usernametxtfield.getText();
        String password = passwordtxtfield.getText();
        if(username.isEmpty() && password.isEmpty() ){
            JOptionPane.showMessageDialog(null, "Please enter both username and password.", "Login Error", JOptionPane.ERROR_MESSAGE);
        }
        else if(!username.equals("admin")||!password.equals("admin")){
            JOptionPane.showMessageDialog(null, "Username and Password mismatch", "Login Error", JOptionPane.ERROR_MESSAGE);
        }
        else {
            panelmain.setVisible(true);
            loginpage.setVerifyInputWhenFocusTarget(false);

        }
    }//GEN-LAST:event_loginbuttonActionPerformed

    private void usernametxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernametxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernametxtfieldActionPerformed
    private void addshippingdata(Shipping ship) {
        shiplist.add(ship);
        //Table add
        DefaultTableModel defaultTableModel = (DefaultTableModel) tblship.getModel();
        defaultTableModel.addRow(new Object[]{
            ship.getFrom(), ship.getTo(), ship.getPickup(),
            ship.getDrop(), ship.getNumber()
        });
    }
    private void registership (Shipping shipping){
    shiplist.add(shipping);
    DefaultTableModel model = (DefaultTableModel) tblship.getModel();
    model.addRow(new Object[]{
       shipping.getFrom(),shipping.getTo(),shipping.getPickup(),shipping.getDrop(),shipping.getNumber()
    });
    }
    private Boolean deleteship(String number){
    String no=number;
    for(Shipping deletestudent:shiplist){
        if (no.equals(deletestudent.getNumber())){
            shiplist.remove(deletestudent);
            return true;
        }
        else{
            return false;
        }
    }
    return false;
    }
    private Boolean updateship(Shipping ship){
        String number=ship.getNumber();
        for (Shipping shipupdate:shiplist){
          if(number.equals(shipupdate.getNumber())){
             shipupdate.setFrom(ship.getFrom());
             shipupdate.setTo(ship.getTo());
             shipupdate.setPickup(ship.getPickup());
             shipupdate.setDrop(ship.getDrop());
             shipupdate.setNumber(ship.getNumber());
              return true;
              }
        }
     return false;
     }
    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(() -> {
            new shippingmain().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel businessship;
    private javax.swing.JButton create;
    private javax.swing.JButton delete;
    private javax.swing.JTextArea droptxtfield;
    private javax.swing.JPanel footer;
    private javax.swing.JComboBox<String> fromoption;
    private javax.swing.JPanel header3;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton login3;
    private javax.swing.JLabel loginbackground;
    private javax.swing.JButton loginbutton;
    private javax.swing.JPanel loginpage;
    private javax.swing.JLabel logo3;
    private javax.swing.JTextArea numbertxtfield;
    private javax.swing.JPanel panelmain;
    private javax.swing.JPasswordField passwordtxtfield;
    private javax.swing.JTextArea pickuptxtfield;
    private javax.swing.JLabel ship6;
    private javax.swing.JLabel ship7;
    private javax.swing.JPanel shiplog;
    private javax.swing.JTabbedPane tabpane;
    private javax.swing.JTable tblship;
    private javax.swing.JComboBox<String> tooption;
    private javax.swing.JButton update;
    private javax.swing.JTextField usernametxtfield;
    // End of variables declaration//GEN-END:variables

}
